export const seedTasks = [
  // Phase 1 — Registration & Auth
  {
    id: "AUTH-01",
    service: "Auth Service",
    task: "User registration endpoint (patient & doctor)",
    priority: "Critical",
    sp: 3,
    rationale: "Core entry point for all users",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "AUTH-02",
    service: "Auth Service",
    task: "JWT login & token issuance",
    priority: "Critical",
    sp: 5,
    rationale: "Blocks every other service",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "AUTH-03",
    service: "Auth Service",
    task: "Role-based access control middleware",
    priority: "Critical",
    sp: 5,
    rationale: "Required before any protected route",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "AUTH-04",
    service: "Auth Service",
    task: "Token refresh and logout",
    priority: "High",
    sp: 2,
    rationale: "Security hygiene, fairly standard",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "AUTH-05",
    service: "Auth Service",
    task: "API Gateway routing to microservices",
    priority: "Critical",
    sp: 8,
    rationale: "Most complex infra piece of auth layer",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "AUTH-06",
    service: "Auth Service",
    task: "Request validation & error handling at gateway",
    priority: "High",
    sp: 3,
    rationale: "Needed before integration testing",
    assignedTo: "Dahami",
    status: "Pending",
  },

  // Phase 2 — Patient Profile Setup
  {
    id: "PAT-01",
    service: "Patient Management",
    task: "Patient registration & profile creation",
    priority: "Critical",
    sp: 3,
    rationale: "Foundational — needed by booking",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAT-02",
    service: "Patient Management",
    task: "View & update patient profile",
    priority: "High",
    sp: 2,
    rationale: "CRUD, moderate effort",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAT-03",
    service: "Patient Management",
    task: "Upload medical reports/documents",
    priority: "High",
    sp: 5,
    rationale: "File handling, storage integration",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "PAT-04",
    service: "Patient Management",
    task: "View uploaded medical history",
    priority: "High",
    sp: 3,
    rationale: "Read + filter, moderate complexity",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "PAT-05",
    service: "Patient Management",
    task: "View past prescriptions",
    priority: "Medium",
    sp: 2,
    rationale: "Read-only, depends on Doctor service",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAT-06",
    service: "Patient Management",
    task: "Account deactivation (admin-triggered)",
    priority: "Low",
    sp: 1,
    rationale: "Simple flag update",
    assignedTo: "Aman",
    status: "Pending",
  },

  // Phase 3 — Doctor Setup
  {
    id: "DOC-01",
    service: "Doctor Management",
    task: "Doctor registration & profile creation",
    priority: "Critical",
    sp: 3,
    rationale: "Parallel to PAT-01, foundational",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "DOC-02",
    service: "Doctor Management",
    task: "View & update doctor profile (specialty, bio, fees)",
    priority: "High",
    sp: 2,
    rationale: "CRUD with extra fields",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "DOC-03",
    service: "Doctor Management",
    task: "Set weekly availability schedule (time slots)",
    priority: "Critical",
    sp: 8,
    rationale: "Complex scheduling logic, slot generation",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "DOC-07",
    service: "Doctor Management",
    task: "View own upcoming & past appointments",
    priority: "Medium",
    sp: 2,
    rationale: "Read-only dashboard feed",
    assignedTo: "Thisuri",
    status: "Pending",
  },

  // Phase 4 — Browse & Book Appointment
  {
    id: "APT-01",
    service: "Appointment Service",
    task: "Browse & search doctors by specialty/availability",
    priority: "Critical",
    sp: 5,
    rationale: "Main discovery flow, filter logic",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "APT-02",
    service: "Appointment Service",
    task: "Book an appointment (select doctor, date, slot)",
    priority: "Critical",
    sp: 7,
    rationale: "Core feature — ties Patient + Doctor + Payment",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "APT-03",
    service: "Appointment Service",
    task: "View appointment details & status",
    priority: "High",
    sp: 2,
    rationale: "Simple read with status enum",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "APT-04",
    service: "Appointment Service",
    task: "Modify (reschedule) an existing appointment",
    priority: "Medium",
    sp: 3,
    rationale: "Conflict check + slot update",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "APT-05",
    service: "Appointment Service",
    task: "Cancel an appointment",
    priority: "High",
    sp: 3,
    rationale: "Slot re-release + notification trigger",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "APT-06",
    service: "Appointment Service",
    task: "Real-time appointment status tracking",
    priority: "High",
    sp: 3,
    rationale: "Polling-based status updates",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "APT-07",
    service: "Appointment Service",
    task: "Prevent double-booking of same time slot",
    priority: "Medium",
    sp: 2,
    rationale: "Concurrency guard",
    assignedTo: "Aman",
    status: "Pending",
  },

  // Phase 5 — Payment
  {
    id: "PAY-01",
    service: "Payment Service",
    task: "Calculate consultation fee from doctor profile",
    priority: "High",
    sp: 2,
    rationale: "Simple lookup",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "PAY-02",
    service: "Payment Service",
    task: "Initiate payment at booking confirmation",
    priority: "Critical",
    sp: 5,
    rationale: "Ties appointment booking to payment gate",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAY-03",
    service: "Payment Service",
    task: "Payment gateway integration (PayHere/Stripe sandbox)",
    priority: "Critical",
    sp: 8,
    rationale: "Third-party SDK, webhook config, testing",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAY-04",
    service: "Payment Service",
    task: "Handle payment success & failure callbacks",
    priority: "Critical",
    sp: 5,
    rationale: "Webhook handling, state machine logic",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAY-05",
    service: "Payment Service",
    task: "Generate payment receipt/confirmation record",
    priority: "High",
    sp: 2,
    rationale: "Store + expose read endpoint",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "PAY-06",
    service: "Payment Service",
    task: "View payment history (patient side)",
    priority: "Medium",
    sp: 2,
    rationale: "Filtered read, low complexity",
    assignedTo: "Aman",
    status: "Pending",
  },

  // Phase 6 — Doctor Accepts
  {
    id: "DOC-04",
    service: "Doctor Management",
    task: "Accept or reject appointment requests",
    priority: "High",
    sp: 3,
    rationale: "Triggers notifications downstream",
    assignedTo: "Dahami",
    status: "Pending",
  },

  // Phase 7 — Video Consultation
  {
    id: "TEL-01",
    service: "Telemedicine Service",
    task: "Generate unique video session room per appointment",
    priority: "Critical",
    sp: 5,
    rationale: "Token/room generation via Agora/Twilio API",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "TEL-02",
    service: "Telemedicine Service",
    task: "Patient joins video consultation",
    priority: "Critical",
    sp: 5,
    rationale: "Token validation + SDK integration",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "TEL-03",
    service: "Telemedicine Service",
    task: "Doctor starts/ends video session",
    priority: "Critical",
    sp: 3,
    rationale: "Session lifecycle management",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "TEL-04",
    service: "Telemedicine Service",
    task: "Third-party video API integration (Agora/Twilio/Jitsi)",
    priority: "Critical",
    sp: 3,
    rationale: "New SDK, auth flows",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "TEL-05",
    service: "Telemedicine Service",
    task: "Session access control (only booked users)",
    priority: "High",
    sp: 3,
    rationale: "Guard with appointment record check",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "TEL-06",
    service: "Telemedicine Service",
    task: "Mark consultation as completed after session ends",
    priority: "High",
    sp: 2,
    rationale: "Status update, triggers prescription flow",
    assignedTo: "Imadh",
    status: "Pending",
  },

  // Phase 8 — Prescription
  {
    id: "DOC-05",
    service: "Doctor Management",
    task: "Issue digital prescriptions after consultation",
    priority: "High",
    sp: 5,
    rationale: "New entity, write + notify patient",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "DOC-06",
    service: "Doctor Management",
    task: "View patient-uploaded reports during session",
    priority: "Medium",
    sp: 2,
    rationale: "Read from Patient service, access guard",
    assignedTo: "Imadh",
    status: "Pending",
  },

  // Phase 9 — Notifications
  {
    id: "NOT-01",
    service: "Notification Service",
    task: "Email confirmation on appointment booking",
    priority: "High",
    sp: 2,
    rationale: "Template + email service integration",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "NOT-02",
    service: "Notification Service",
    task: "SMS confirmation on appointment booking",
    priority: "High",
    sp: 2,
    rationale: "Similar setup, different SDK",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "NOT-03",
    service: "Notification Service",
    task: "Reminder notification before appointment",
    priority: "Medium",
    sp: 3,
    rationale: "Scheduled job/cron, time-aware logic",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "NOT-04",
    service: "Notification Service",
    task: "Notify doctor on new appointment booked",
    priority: "High",
    sp: 2,
    rationale: "Event-driven, low extra logic",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "NOT-05",
    service: "Notification Service",
    task: "Notify patient on accept/reject by doctor",
    priority: "High",
    sp: 2,
    rationale: "Triggered by DOC-04",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "NOT-06",
    service: "Notification Service",
    task: "Notify patient after consultation with prescription link",
    priority: "Medium",
    sp: 2,
    rationale: "Triggered by TEL-06 + DOC-05",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "NOT-07",
    service: "Notification Service",
    task: "Integrate third-party email service (SendGrid/Mailgun)",
    priority: "High",
    sp: 2,
    rationale: "API key config, template setup",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "NOT-08",
    service: "Notification Service",
    task: "Integrate third-party SMS service (Twilio/Notify.lk)",
    priority: "High",
    sp: 2,
    rationale: "Similar setup, country-specific for LK",
    assignedTo: "Dahami",
    status: "Pending",
  },

  // Phase 10 — History & Admin
  {
    id: "ADM-01",
    service: "Admin Service",
    task: "View all registered patients",
    priority: "Medium",
    sp: 1,
    rationale: "Admin read, simple list",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "ADM-02",
    service: "Admin Service",
    task: "View all registered doctors",
    priority: "Medium",
    sp: 1,
    rationale: "Admin read, simple list",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "ADM-03",
    service: "Admin Service",
    task: "Verify/approve doctor registrations",
    priority: "High",
    sp: 3,
    rationale: "Approval workflow, status update",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "ADM-04",
    service: "Admin Service",
    task: "Suspend or deactivate user account",
    priority: "Medium",
    sp: 2,
    rationale: "Flag update + auth guard effect",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "ADM-05",
    service: "Admin Service",
    task: "View all appointments platform-wide",
    priority: "Medium",
    sp: 2,
    rationale: "Cross-service read, pagination",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "ADM-06",
    service: "Admin Service",
    task: "View all payment/financial transactions",
    priority: "Medium",
    sp: 2,
    rationale: "Read from Payment service",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "ADM-07",
    service: "Admin Service",
    task: "Admin dashboard with key metrics",
    priority: "Low",
    sp: 2,
    rationale: "Aggregation query",
    assignedTo: "Dahami",
    status: "Pending",
  },

  // AI Symptom Checker (Optional)
  {
    id: "AI-01",
    service: "AI Symptom Checker",
    task: "Patient symptom input form & API endpoint",
    priority: "Low",
    sp: 2,
    rationale: "Optional feature, simple form",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "AI-02",
    service: "AI Symptom Checker",
    task: "Send symptoms to AI/ML API (OpenAI/Gemini)",
    priority: "Low",
    sp: 5,
    rationale: "Prompt engineering + API integration",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "AI-03",
    service: "AI Symptom Checker",
    task: "Return preliminary health suggestions",
    priority: "Low",
    sp: 3,
    rationale: "Parse AI response, format output",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "AI-04",
    service: "AI Symptom Checker",
    task: "Recommend doctor specialties from symptoms",
    priority: "Low",
    sp: 3,
    rationale: "Map AI output to specialty taxonomy",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "AI-05",
    service: "AI Symptom Checker",
    task: "Log symptom check history per patient",
    priority: "Low",
    sp: 2,
    rationale: "Simple write + patient-scoped read",
    assignedTo: "Thisuri",
    status: "Pending",
  },

  // Frontend
  {
    id: "FE-01",
    service: "Frontend",
    task: "Landing page with doctor browsing & search UI",
    priority: "Critical",
    sp: 5,
    rationale: "First impression, search integration",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "FE-02",
    service: "Frontend",
    task: "Patient registration & login UI",
    priority: "Critical",
    sp: 3,
    rationale: "Forms + JWT storage",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "FE-03",
    service: "Frontend",
    task: "Doctor registration & login UI",
    priority: "Critical",
    sp: 3,
    rationale: "Similar to FE-02 with extra fields",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "FE-04",
    service: "Frontend",
    task: "Patient dashboard (appointments, prescriptions, reports)",
    priority: "High",
    sp: 5,
    rationale: "Multi-section, multiple API calls",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "FE-05",
    service: "Frontend",
    task: "Doctor dashboard (schedule, patients, appointments)",
    priority: "High",
    sp: 5,
    rationale: "Calendar or list view, moderate effort",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "FE-06",
    service: "Frontend",
    task: "Admin dashboard UI",
    priority: "Medium",
    sp: 3,
    rationale: "Metrics, tables, management actions",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "FE-07",
    service: "Frontend",
    task: "Appointment booking flow UI",
    priority: "Critical",
    sp: 6,
    rationale: "Multi-step wizard, calendar, payment hand-off",
    assignedTo: "Aman",
    status: "Pending",
  },
  {
    id: "FE-08",
    service: "Frontend",
    task: "Video consultation UI (Agora/Twilio widget embed)",
    priority: "High",
    sp: 5,
    rationale: "SDK embed, layout, controls",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "FE-09",
    service: "Frontend",
    task: "Payment checkout UI",
    priority: "High",
    sp: 3,
    rationale: "Gateway redirect or embed",
    assignedTo: "Dahami",
    status: "Pending",
  },
  {
    id: "FE-10",
    service: "Frontend",
    task: "AI symptom checker UI",
    priority: "Low",
    sp: 2,
    rationale: "Optional, simple form + result display",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "FE-11",
    service: "Frontend",
    task: "Responsive design across devices",
    priority: "High",
    sp: 3,
    rationale: "CSS polish across all pages",
    assignedTo: "Imadh",
    status: "Pending",
  },

  // Infrastructure
  {
    id: "INF-01",
    service: "Infrastructure",
    task: "Dockerize each microservice",
    priority: "Critical",
    sp: 8,
    rationale: "One Dockerfile per service, 8+ services",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "INF-02",
    service: "Infrastructure",
    task: "Kubernetes deployment manifests",
    priority: "Critical",
    sp: 8,
    rationale: "Deployments, services, ingress per service",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "INF-03",
    service: "Infrastructure",
    task: "Docker Compose for local development",
    priority: "High",
    sp: 3,
    rationale: "Dev DX, port mappings, shared network",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "INF-04",
    service: "Infrastructure",
    task: "GitHub repo with structured directory layout",
    priority: "High",
    sp: 2,
    rationale: "One-time setup, clear convention",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "INF-05",
    service: "Infrastructure",
    task: "Environment variable management (.env / K8s secrets)",
    priority: "High",
    sp: 3,
    rationale: "Security-critical, all services affected",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "INF-06",
    service: "Infrastructure",
    task: "Database setup scripts per service",
    priority: "High",
    sp: 5,
    rationale: "Schema + seed scripts, 6+ databases",
    assignedTo: "Imadh",
    status: "Pending",
  },
  {
    id: "INF-07",
    service: "Infrastructure",
    task: "README with deployment steps",
    priority: "Medium",
    sp: 2,
    rationale: "Deliverable requirement",
    assignedTo: "Imadh",
    status: "Pending",
  },

  // Report
  {
    id: "RPT-01",
    service: "Report",
    task: "High-level architecture diagram",
    priority: "High",
    sp: 3,
    rationale: "Deliverable, requires design time",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "RPT-02",
    service: "Report",
    task: "Service interface list (REST endpoints per service)",
    priority: "High",
    sp: 3,
    rationale: "Compile from all services",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "RPT-03",
    service: "Report",
    task: "Workflow diagrams (booking, payment, video flow)",
    priority: "Medium",
    sp: 3,
    rationale: "3 diagrams, moderate effort",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "RPT-04",
    service: "Report",
    task: "Auth & security mechanism explanation",
    priority: "Medium",
    sp: 2,
    rationale: "Write-up, not much research needed",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "RPT-05",
    service: "Report",
    task: "Individual contributions section",
    priority: "High",
    sp: 1,
    rationale: "Each member writes their own part",
    assignedTo: "Thisuri",
    status: "Pending",
  },
  {
    id: "RPT-06",
    service: "Report",
    task: "Full code appendix (text, not screenshots)",
    priority: "High",
    sp: 2,
    rationale: "Copy-paste, formatting effort only",
    assignedTo: "Thisuri",
    status: "Pending",
  },
];
